"use client";
import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";
import { SessionProvider, signIn } from "next-auth/react";
import { cn } from "@/lib/utils";
import MainSidebar from "@/components/MainSidebar";
import React, { useContext, useState } from "react";
import { IsLoginContext } from "@/lib/Context";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { GithubLogo, GoogleLogo } from "@/components/Svg";
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [IsLogin, SetIsLogin] = useState(false);

  return (
    <SessionProvider>
      <IsLoginContext.Provider value={{ IsLogin, SetIsLogin }}>
        <html lang="en">
          <body className={cn(`${GeistMono.className} antialiased `)}>
            <div className="flex flex-col min-h-screen bg-gradient-to-br from-[#141414] via-[#222222]  to-[#383737]   ">
              {IsLogin && (
                <div
                  onClick={() => {
                    SetIsLogin(false);
                  }}
                  className="flex items-center justify-center w-screen h-screen  z-30 absolute  backdrop-blur-sm    "
                >
                  <div
                    onClick={(e) => e.stopPropagation()}
                    className={cn(
                      "flex flex-col w-[500px]  bg-[#1A1A1A]  p-10 rounded-xl gap-6"
                    )}
                  >
                    <div className="flex flex-col gap-6">
                      <div className="flex flex-col items-center gap-2">
                        <h1 className="text-xl font-bold">Welcome to Vstack</h1>
                        <div className="text-center text-sm">
                          Don&apos;t have an account?{" "}
                          <a
                            href="#"
                            className="underline cursor-not-allowed underline-offset-4"
                          >
                            Sign up
                          </a>
                        </div>
                      </div>
                      <div className="flex flex-col gap-6">
                        <div className="grid gap-2">
                          <Label htmlFor="email">Email</Label>
                          <Input
                            disabled
                            id="email"
                            type="email"
                            placeholder="m@example.com"
                            required
                          />
                        </div>
                        <Button disabled type="submit" className="w-full">
                          Login
                        </Button>
                      </div>
                      <div className="relative text-center text-sm after:absolute after:inset-0 after:top-1/2 after:z-0 after:flex after:items-center after:border-t after:border-border">
                        <span className="relative z-10  px-2 text-muted-foreground">
                          Or
                        </span>
                      </div>
                      <div className="grid gap-4 sm:grid-cols-2">
                        <Button
                          onClick={() => signIn("github")}
                          variant="outline"
                          className="w-full bg-[#1A1A1A]"
                        >
                          <GithubLogo />
                          Continue with Github
                        </Button>
                        <Button
                          onClick={() => signIn("google")}
                          variant="outline"
                          className="w-full bg-[#1A1A1A]"
                        >
                          <GoogleLogo className="w-3 h-3" />
                          Continue with Google
                        </Button>
                      </div>
                    </div>

                    <div className=" text-balance text-center text-xs text-muted-foreground [&_a]:underline [&_a]:underline-offset-4 hover:[&_a]:text-primary  ">
                      By clicking continue, you agree to our{" "}
                      <a href="#">Terms of Service</a> and{" "}
                      <a href="#">Privacy Policy</a>.
                    </div>
                  </div>
                </div>
              )}
              <MainSidebar />
              {children}
            </div>
          </body>
        </html>
      </IsLoginContext.Provider>
    </SessionProvider>
  );
}
