import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { cn } from "@/lib/utils";
import MainSidebar from "@/components/MainSidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
      <html lang="en">
        <body className={cn(`${GeistMono.className} antialiased    `)}>
          <div className="flex flex-col min-h-screen">
            <MainSidebar />
            {children}
          </div>
        </body>
      </html>
    </SessionProvider>
  );
}
