import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { cn } from "@/lib/utils";
import MainSidebar from "@/components/sidebar/mainSidebar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const MOBILE_BREAKPOINT = 768;

  return (
    <SessionProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased  `}
        >
          <div className="md:block hidden">
            <MainSidebar />
            {children}
          </div>
          <div className="md:hidden">
            <h1>Not availaaiug</h1>
          </div>
        </body>
      </html>
    </SessionProvider>
  );
}
